In [410]:
import pandas as pd
import numpy as np

In [411]:
data = pd.read_json('mb2016.json')
normalized = pd.json_normalize(data["data"])

In [412]:
data

       total                                               data
0      59506  {'name': 'Far from the Madding Crowd', 'grade'...
1      59506  {'name': 'Wuthering Heights', 'grade': '6B+', ...
2      59506  {'name': 'Problem 3', 'grade': '6B+', 'userGra...
3      59506  {'name': 'HARD TIMES', 'grade': '7A', 'userGra...
4      59506  {'name': 'Problem 5', 'grade': '7A', 'userGrad...
...      ...                                                ...
59501  59506  {'name': 'KVT6', 'grade': '6B+', 'userGrade': ...
59502  59506  {'name': 'KVT7', 'grade': '6B+', 'userGrade': ...
59503  59506  {'name': 'KVT8', 'grade': '6B+', 'userGrade': ...
59504  59506  {'name': 'KVT9', 'grade': '6B+', 'userGrade': ...
59505  59506  {'name': 'KVT10', 'grade': '6B+', 'userGrade':...

[59506 rows x 2 columns]

In [413]:
normalized[["grade", "userGrade", "userRating", "repeats", "moves"]]

SCALE = 20

def repeat_weight(repeats):
    return np.tanh(repeats / SCALE)

normalized["repeat_weight"] = normalized[["repeats"]].apply(repeat_weight, axis=1)
normalized

,name,grade,userGrade,setbyId,setby,method,userRating,repeats,isBenchmark,isMaster,...,hasBetaVideo,moonBoardConfigurationId,apiId,dateInserted,dateUpdated,dateDeleted,holdsetup.description,holdsetup.holdsets,holdsetup.apiId,repeat_weight
0,Far from the Madding Crowd,6B+,6B+,5FC09F63-05F3-4DAE-A1A5-3AC22C37139A,Ben Moon,Feet follow hands,4,24993,True,False,...,True,0,19215,2016-03-01T10:00:27,2023-01-30T19:49:50.173,None,MoonBoard 2016,None,1,1.0
1,Wuthering Heights,6B+,6B+,5FC09F63-05F3-4DAE-A1A5-3AC22C37139A,Ben Moon,Feet follow hands,4,35673,True,False,...,True,0,19216,2016-03-01T10:00:27,2023-01-30T19:31:30.057,None,MoonBoard 2016,None,1,1.0
2,Problem 3,6B+,6B+,CC7D7BD1-67CD-4027-A537-22E7855C18B7,Ally Patrick,Feet follow hands,4,757,False,False,...,False,0,19217,2016-03-01T10:00:16,2023-01-30T15:33:23.043,None,MoonBoard 2016,None,1,1.0
3,HARD TIMES,7A,7A,5FC09F63-05F3-4DAE-A1A5-3AC22C37139A,Ben Moon,Feet follow hands,5,8670,True,False,...,True,0,19218,2016-03-01T10:00:15,2023-01-30T20:54:43.59,None,MoonBoard 2016,None,1,1.0
4,Problem 5,7A,7A,CC7D7BD1-67CD-4027-A537-22E7855C18B7,Ally Patrick,Feet follow hands,4,255,False,False,...,False,0,19219,2016-03-01T10:00:15,2023-01-02T18:11:39.877,None,MoonBoard 2016,None,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59501,KVT6,6B+,None,0924d8c6-0f0c-4e13-aae5-5e729189674b,TCAMILLIERI,Feet follow hands,0,0,False,False,...,False,0,462575,2023-01-30T20:59:39.577,None,None,MoonBoard 2016,None,1,0.0
59502,KVT7,6B+,None,0924d8c6-0f0c-4e13-aae5-5e729189674b,TCAMILLIERI,Feet follow hands,0,0,False,False,...,False,0,462577,2023-01-30T21:02:38.843,None,None,MoonBoard 2016,None,1,0.0
59503,KVT8,6B+,None,0924d8c6-0f0c-4e13-aae5-5e729189674b,TCAMILLIERI,Feet follow hands,0,0,False,False,...,False,0,462579,2023-01-30T21:05:29.5,None,None,MoonBoard 2016,None,1,0.0
59504,KVT9,6B+,None,0924d8c6-0f0c-4e13-aae5-5e729189674b,TCAMILLIERI,Feet follow hands,0,0,False,False,...,False,0,462580,2023-01-30T21:07:46.393,None,None,MoonBoard 2016,None,1,0.0
59505,KVT10,6B+,None,0924d8c6-0f0c-4e13-aae5-5e729189674b,TCAMILLIERI,Feet follow hands,0,0,False,False,...,False,0,462581,2023-01-30T21:11:36.463,None,None,MoonBoard 2016,None,1,0.0

In [414]:
normalized["moves"][0]

[{'problemId': 19215, 'description': 'E6', 'isStart': True, 'isEnd': False},
 {'problemId': 19215, 'description': 'C5', 'isStart': True, 'isEnd': False},
 {'problemId': 19215, 'description': 'E8', 'isStart': False, 'isEnd': False},
 {'problemId': 19215, 'description': 'F11', 'isStart': False, 'isEnd': False},
 {'problemId': 19215, 'description': 'C13', 'isStart': False, 'isEnd': False},
 {'problemId': 19215, 'description': 'D15', 'isStart': False, 'isEnd': False},
 {'problemId': 19215, 'description': 'D18', 'isStart': False, 'isEnd': True}]

In [415]:
movelist = pd.json_normalize(normalized["moves"][0])[["description", "isStart", "isEnd"]]

In [416]:
movelist = pd.json_normalize(normalized["moves"][0])

In [417]:
movelist

   problemId description  isStart  isEnd
0      19215          E6     True  False
1      19215          C5     True  False
2      19215          E8    False  False
3      19215         F11    False  False
4      19215         C13    False  False
5      19215         D15    False  False
6      19215         D18    False   True

In [418]:
board = np.zeros((18, 11, 3), dtype=float)

print_dict = {
    0: "M",
    1: "S",
    2: "E"
}

def print_board_bar():
    for i in range(26):
        print("-", end="")
    print()

def print_board(board):
    print(" "*3, end="| ")
    for i in range(11):
        print(f"{chr(i + 65)}", end=" ")
    print()
    print_board_bar()
    for i in range(18):
        print(f"{18 - i:2} |", end=" ")
        for j in range(11):
            num_printed = False
            for c in range(2):
                if board[17 - i, j, c] > 0:
                    char = "E"
                    if c > 0:
                        char = "S" if i >= 12 else "E"
                    print(char, end=" ")  
                    num_printed = True
            if not num_printed:
                print("-", end=" ")
        print()
    print_board_bar()

def add_move(board, moveString, isStart, isEnd):
    row = int(moveString[1:]) - 1
    col = ord(moveString[0]) - 65
    if col >= 0 and col < 11: # matched starts are sometimes indicated with lowercase letters, but we don't need them (for now, may add them later)
        board[row, col, int(isStart) + 2 * int(isEnd)] = 1

for idx, move in movelist.iterrows():
    add_move(board, move.description, move.isStart, move.isEnd)

print_board(board)

   | A B C D E F G H I J K
--------------------------
18 | - - - - - - - - - - -
17 | - - - - - - - - - - -
16 | - - - - - - - - - - -
15 | - - - E - - - - - - -
14 | - - - - - - - - - - -
13 | - - E - - - - - - - -
12 | - - - - - - - - - - -
11 | - - - - - E - - - - -
10 | - - - - - - - - - - -
 9 | - - - - - - - - - - -
 8 | - - - - E - - - - - -
 7 | - - - - - - - - - - -
 6 | - - - - S - - - - - -
 5 | - - S - - - - - - - -
 4 | - - - - - - - - - - -
 3 | - - - - - - - - - - -
 2 | - - - - - - - - - - -
 1 | - - - - - - - - - - -
--------------------------

In [419]:
boards = np.zeros((18, 11, 100))

In [420]:
filtered = normalized[["grade", "userGrade", "userRating", "moves", "repeat_weight", "repeats"]]
filtered = filtered[filtered["repeats"] > 3]
filtered = filtered[filtered["userRating"] > 3]
filtered = filtered[filtered["grade"] != "8B+"]

In [421]:
# One hot encoding method for use in ordinal regression networks
# Classification networks "Classify" based on the classes given, and are able to more directly learn the ordinality of the data
# Think of classes as P(Grade > x) for each x in list, (x0 = 6B+, x1 = 6C, and so on)
# There are so few examples of hard and repeated problems that they are combined together as 8A and up (seems reasonable from my experience on the moonboard anyways)
grade_dict = {
    "6B+": np.array([0,0,0,0,0,0,0]),
    "6C": np.array([1,0,0,0,0,0,0]), 
    "6C+": np.array([1,0,0,0,0,0,0]), # both 6C and 6C+ are V5
    "7A": np.array([1,1,0,0,0,0,0]),
    "7A+": np.array([1,1,1,0,0,0,0]),
    "7B": np.array([1,1,1,1,0,0,0]), # both 7B and 7B+ are V8
    "7B+": np.array([1,1,1,1,0,0,0]),
    "7C": np.array([1,1,1,1,1,0,0]),
    "7C+": np.array([1,1,1,1,1,1,0]),
    "8A": np.array([1,1,1,1,1,1,1]), # 8A and up are considered the same (very difficult and vary wildly in true difficulty)
    "8A+": np.array([1,1,1,1,1,1,1]),
    "8B": np.array([1,1,1,1,1,1,1]),
}

grade_num_dict = {
    "6B+": 0,
    "6C": 1, 
    "6C+": 1, # both 6C and 6C+ are V5
    "7A": 2,
    "7A+": 3,
    "7B": 4, # both 7B and 7B+ are V8
    "7B+": 4,
    "7C": 5,
    "7C+": 6,
    "8A": 7, # 8A and up are considered the same (very difficult and vary wildly in true difficulty, + not enough examples)
    "8A+": 7,
    "8B": 7,
}

In [422]:
filtered

,grade,userGrade,userRating,moves,repeat_weight,repeats
0,6B+,6B+,4,"[{'problemId': 19215, 'description': 'E6', 'is...",1.000000,24993
1,6B+,6B+,4,"[{'problemId': 19216, 'description': 'F5', 'is...",1.000000,35673
2,6B+,6B+,4,"[{'problemId': 19217, 'description': 'F5', 'is...",1.000000,757
3,7A,7A,5,"[{'problemId': 19218, 'description': 'B10', 'i...",1.000000,8670
4,7A,7A,4,"[{'problemId': 19219, 'description': 'C5', 'is...",1.000000,255
...,...,...,...,...,...,...
59441,6C,6C,4,"[{'problemId': 462415, 'description': 'F5', 'i...",0.197375,4
59462,6B+,6B+,4,"[{'problemId': 462472, 'description': 'F5', 'i...",0.244919,5
59465,6B+,6B+,4,"[{'problemId': 462475, 'description': 'G2', 'i...",0.197375,4
59484,6B+,6B+,4,"[{'problemId': 462524, 'description': 'G4', 'i...",0.244919,5
59491,6B+,6B+,4,"[{'problemId': 462536, 'description': 'K5', 'i...",0.197375,4

In [423]:
def board_from_moves(moves):
    moveList = pd.json_normalize(moves.iloc[0])[["description", "isStart", "isEnd"]]
    board_int = np.zeros((18, 11, 3), dtype=float)
    board_final = np.zeros((18, 11, 2), dtype=float)
    for idx, move in moveList.iterrows():
        add_move(board_int, move.description, move.isStart, move.isEnd)
    # adjust for two vs one hand start / finish
    board_int[:, :, 1] /= np.sum(board_int[:, :, 1])
    board_int[:, :, 2] /= np.sum(board_int[:, :, 2])
    board_final[:, :, 0] = board_int[:, :, 0]
    board_final[:, :, 1] = np.maximum(board_int[:, :, 1], board_int[:, :, 2])
    return board_final

In [424]:
filtered["numberGrade"] = filtered["userGrade"].map(grade_dict)
filtered["numberGrade"].fillna(filtered["grade"].map(grade_dict), inplace=True)
filtered['board'] = filtered[["moves"]].apply(board_from_moves, axis=1)

filtered["grade_numeric"] = filtered["userGrade"].map(grade_num_dict)
filtered["grade_numeric"].fillna(filtered["grade"].map(grade_num_dict), inplace=True)

In [425]:
filtered

,grade,userGrade,userRating,moves,repeat_weight,repeats,numberGrade,board,grade_numeric
0,6B+,6B+,4,"[{'problemId': 19215, 'description': 'E6', 'is...",1.000000,24993,"[0, 0, 0, 0, 0, 0, 0]","[[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0....",0.0
1,6B+,6B+,4,"[{'problemId': 19216, 'description': 'F5', 'is...",1.000000,35673,"[0, 0, 0, 0, 0, 0, 0]","[[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0....",0.0
2,6B+,6B+,4,"[{'problemId': 19217, 'description': 'F5', 'is...",1.000000,757,"[0, 0, 0, 0, 0, 0, 0]","[[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0....",0.0
3,7A,7A,5,"[{'problemId': 19218, 'description': 'B10', 'i...",1.000000,8670,"[1, 1, 0, 0, 0, 0, 0]","[[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0....",2.0
4,7A,7A,4,"[{'problemId': 19219, 'description': 'C5', 'is...",1.000000,255,"[1, 1, 0, 0, 0, 0, 0]","[[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0....",2.0
...,...,...,...,...,...,...,...,...,...
59441,6C,6C,4,"[{'problemId': 462415, 'description': 'F5', 'i...",0.197375,4,"[1, 0, 0, 0, 0, 0, 0]","[[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0....",1.0
59462,6B+,6B+,4,"[{'problemId': 462472, 'description': 'F5', 'i...",0.244919,5,"[0, 0, 0, 0, 0, 0, 0]","[[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0....",0.0
59465,6B+,6B+,4,"[{'problemId': 462475, 'description': 'G2', 'i...",0.197375,4,"[0, 0, 0, 0, 0, 0, 0]","[[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0....",0.0
59484,6B+,6B+,4,"[{'problemId': 462524, 'description': 'G4', 'i...",0.244919,5,"[0, 0, 0, 0, 0, 0, 0]","[[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0....",0.0
59491,6B+,6B+,4,"[{'problemId': 462536, 'description': 'K5', 'i...",0.197375,4,"[0, 0, 0, 0, 0, 0, 0]","[[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0....",0.0

In [426]:
filtered.iloc[0]["board"]

array([[[0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ]],

       [[0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ]],

       [[0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ]],

       [[0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ]],

       [[0. , 0. ],
        [0. , 0. ],
        [0. , 0.5],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ]],

       [[0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0.5],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ]],

       [[0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ]],

       [[0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [1. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ]],

       [[0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ]],

       [[0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ]],

       [[0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [1. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ]],

       [[0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ]],

       [[0. , 0. ],
        [0. , 0. ],
        [1. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ]],

       [[0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ]],

       [[0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [1. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ]],

       [[0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ]],

       [[0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ]],

       [[0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 1. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ],
        [0. , 0. ]]])

In [427]:
filtered.isna().sum()

grade               0
userGrade        6599
userRating          0
moves               0
repeat_weight       0
repeats             0
numberGrade         8
board               0
grade_numeric       8
dtype: int64

In [428]:
filtered = filtered[filtered["numberGrade"].notna()]
filtered.isna().sum()

grade               0
userGrade        6599
userRating          0
moves               0
repeat_weight       0
repeats             0
numberGrade         0
board               0
grade_numeric       0
dtype: int64

In [429]:
filtered[filtered["userGrade"] == "8B+"]

,grade,userGrade,userRating,moves,repeat_weight,repeats,numberGrade,board,grade_numeric
53849,8B,8B+,5,"[{'problemId': 441849, 'description': 'F5', 'i...",0.421899,9,"[1, 1, 1, 1, 1, 1, 1]","[[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0....",7.0

In [430]:
interesting = filtered[filtered["userGrade"] != filtered["grade"]]
interesting = interesting[interesting["userGrade"] != "None"]

In [431]:
interesting

,grade,userGrade,userRating,moves,repeat_weight,repeats,numberGrade,board,grade_numeric
75,6C,None,5,"[{'problemId': 19669, 'description': 'D5', 'is...",0.291313,6,"[1, 0, 0, 0, 0, 0, 0]","[[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0....",1.0
86,7A,7B,5,"[{'problemId': 19786, 'description': 'A5', 'is...",0.980096,46,"[1, 1, 1, 1, 0, 0, 0]","[[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0....",4.0
93,7B,None,4,"[{'problemId': 19907, 'description': 'D3', 'is...",0.336376,7,"[1, 1, 1, 1, 0, 0, 0]","[[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0....",4.0
124,6B+,6C,4,"[{'problemId': 20200, 'description': 'F5', 'is...",0.462117,10,"[1, 0, 0, 0, 0, 0, 0]","[[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0....",1.0
136,6B+,None,4,"[{'problemId': 20309, 'description': 'J5', 'is...",0.379949,8,"[0, 0, 0, 0, 0, 0, 0]","[[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0....",0.0
...,...,...,...,...,...,...,...,...,...
58948,6B+,6C,5,"[{'problemId': 460032, 'description': 'B3', 'i...",0.244919,5,"[1, 0, 0, 0, 0, 0, 0]","[[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0....",1.0
59010,6B+,6C,5,"[{'problemId': 460206, 'description': 'F5', 'i...",0.379949,8,"[1, 0, 0, 0, 0, 0, 0]","[[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0....",1.0
59075,6C,6B+,4,"[{'problemId': 460412, 'description': 'K5', 'i...",0.716298,18,"[0, 0, 0, 0, 0, 0, 0]","[[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0....",0.0
59076,7A,6C+,4,"[{'problemId': 460413, 'description': 'K5', 'i...",0.500520,11,"[1, 0, 0, 0, 0, 0, 0]","[[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0....",1.0
59196,6C+,6C,5,"[{'problemId': 460764, 'description': 'B3', 'i...",0.291313,6,"[1, 0, 0, 0, 0, 0, 0]","[[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0....",1.0

In [432]:
filtered['numberGrade'].value_counts()

numberGrade
[0, 0, 0, 0, 0, 0, 0]    11854
[1, 0, 0, 0, 0, 0, 0]     4578
[1, 0, 0, 0, 0, 0, 0]     3358
[1, 1, 0, 0, 0, 0, 0]     2917
[1, 1, 1, 0, 0, 0, 0]     1730
[1, 1, 1, 1, 0, 0, 0]     1246
[1, 1, 1, 1, 0, 0, 0]      883
[1, 1, 1, 1, 1, 0, 0]      537
[1, 1, 1, 1, 1, 1, 0]      262
[1, 1, 1, 1, 1, 1, 1]      100
[1, 1, 1, 1, 1, 1, 1]       16
[1, 1, 1, 1, 1, 1, 1]        3
Name: count, dtype: int64

In [433]:
# since there are so many more V4s and V5s than any others, we are going to drop the least repeated ones to balance out the imbalanced classes
filter_repeat = filtered[filtered['grade_numeric'] == 0]["repeats"].quantile(0.6)
filtered = filtered[(filtered['grade_numeric'] != 0) | (filtered["repeats"] >= filter_repeat)]

filter_repeat = filtered[(filtered['grade_numeric'] == 1)]["repeats"].quantile(0.4)
filtered = filtered[(filtered['grade_numeric'] != 1) | (filtered["repeats"] >= filter_repeat)]
filtered['numberGrade'].value_counts()

numberGrade
[0, 0, 0, 0, 0, 0, 0]    4832
[1, 0, 0, 0, 0, 0, 0]    3299
[1, 1, 0, 0, 0, 0, 0]    2917
[1, 0, 0, 0, 0, 0, 0]    2006
[1, 1, 1, 0, 0, 0, 0]    1730
[1, 1, 1, 1, 0, 0, 0]    1246
[1, 1, 1, 1, 0, 0, 0]     883
[1, 1, 1, 1, 1, 0, 0]     537
[1, 1, 1, 1, 1, 1, 0]     262
[1, 1, 1, 1, 1, 1, 1]     100
[1, 1, 1, 1, 1, 1, 1]      16
[1, 1, 1, 1, 1, 1, 1]       3
Name: count, dtype: int64

In [434]:
filtered.isna().sum()

grade               0
userGrade        3006
userRating          0
moves               0
repeat_weight       0
repeats             0
numberGrade         0
board               0
grade_numeric       0
dtype: int64

In [435]:
test = filtered[["numberGrade", "board"]].reset_index(drop=True)


np.save("board_grade.npy", test.to_numpy())
test["numberGrade"][144]

filtered["numberGrade"][144]

print_board(test.iloc[0].board)
print()
print_board(test.iloc[199].board)

KeyError: 144

In [42]:
filtered.iloc[144]

grade                                                         6B
userGrade                                                     6B
userRating                                                     4
repeats                                                       53
moves          [{'problemId': 20576, 'description': 'H5', 'is...
numberGrade              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
board          [[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], ...
Name: 160, dtype: object

In [243]:
data = np.load('board_grade.npy', allow_pickle=True)

In [244]:
data.shape

(16654, 2)

In [245]:
data[0][1].shape

(18, 11, 2)

In [246]:
data[0][0].shape

(7,)